name: "Component Builder Check"
on:
  pull_request:
    paths:
      - 'containers/fedora/**'
      - '.github/component-builder-config.json'
      - '.github/workflows/component-builder-prepare.yml'
      - '.github/workflows/component-builder-build.yml'
      - '.github/workflows/component-builder.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  prepare:
    uses: ./.github/workflows/component-builder-prepare.yml

  build:
    needs: prepare
    uses: ./.github/workflows/component-builder-build.yml
    with:
      fedora_version: ${{ needs.prepare.outputs.fedora_version }}
      fedora_image_base: ${{ needs.prepare.outputs.fedora_image_base }}
      fedora_checksum_base: ${{ needs.prepare.outputs.fedora_checksum_base }}
      matrix: ${{ needs.prepare.outputs.matrix }}
      remote_repository: ${{ needs.prepare.outputs.remote_repository }}
      no_secrets: true
      upload_artifact: true
